### ISSUE TITLE
SPICE_SEND_PACKET_NL can trigger -Wmaybe-uninitialized

### ISSUE THREAD

**Issue by zer0def** [gnif/PureSpice#1] opened 2020-03-08 08:25 UTC
Since I'm poking around with compiling Looking Glass from master and not altering build flags too much, currently building PureSpice (during LG client build) with the default `-Werror` causes:

```
[ 25%] Linking C static library liblg_common.a
/tmp/PKGBUILDs/src/looking-glass/repos/PureSpice/src/spice.c: In function ‘spice_agent_write_msg’:
/tmp/PKGBUILDs/src/looking-glass/repos/PureSpice/src/spice.c:87:57: error: ‘packet’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   87 |   const ssize_t wrote = send((channel)->socket, header, *sz, 0); \
      |                                                         ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make[2]: *** [PureSpice/CMakeFiles/purespice.dir/build.make:63: PureSpice/CMakeFiles/purespice.dir/src/spice.c.o] Error 
```

which is "solved" by changing the macro back to a function call, as per https://raw.githubusercontent.com/zer0def/PKGBUILDs/looking-glass-git/0001-purespice.patch

Is that intended and/or do you have an idea on how to approach this?

**Comment by gnif** [comment] 2020-03-09 13:09
> Is that intended and/or do you have an idea on how to approach this?

Yes, it is intended, your proposed fix is invalid, if you look at the macro it's actually using some pointer arithmetic so that the Spice mini header is prepended to the packet. By changing things the way you have you are not sending the mini header and the message will be ignored (or cause a disconnect) by the SPICE server.

**Comment by zer0def** [comment] 2020-03-09 13:14
In that case do I just drop `-Werror` and compile it as is?

**Comment by gnif** [comment] 2020-03-09 13:16
It is fine to do so, however it has raised another potential issue, in that `sizeof(void)` is technically invalid even though GCC allows it. I will need to think on this a bit.

even still my version of GCC does not warn or error on this as `*sz` is clearly initialized, what version are you using? This might actually be a GCC bug.

**Comment by gnif** [comment] 2020-03-09 13:18
Wait no, there is actually a pretty nasty arithmetic error there... the warning is correct!

**Comment by zer0def** [comment] 2020-03-09 13:18
GCC is 9.2.1 on Arch.

**Comment by gnif** [comment] 2020-03-09 13:20
Sigh, I should go to bed... midnight here. I am sorry there is no error here. `sz` is correctly set and used. I will see if I can reproduce this tomorrow and verify, thanks.

**Comment by zer0def** [comment] 2020-03-09 14:15
For the record, I'm pretty sure that the warning is just a symptom, because changing only that specific line as in the provided patch silences the issue, especially since the same macro is being used in an initialization condition earlier in the same function, so from my POV either `cont` or GCC's handling of `sizeof(void)` would be the issue's source.

This might help you out in terms of replication:
```
docker run -i archlinux/base /bin/sh <<EOF
pacman --noconfirm -Sy base-devel git
cd /tmp
echo "bin ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudo-bin
su -s /bin/sh -c 'rm -rf PKGBUILDs; git clone https://github.com/zer0def/PKGBUILDs -b looking-glass-git && cd PKGBUILDs && sed -i '\''/patch.*0001-purespice.patch/d'\'' PKGBUILD && makepkg --noconfirm -Csf' bin
EOF
```

**Comment by gnif** [comment] 2020-03-09 14:17
`cont` is just a variable, I think you're confusing this with `const`. I believe it's the `sizeof(void)`, but like I stated I will need to do some more digging.

**Comment by zer0def** [comment] 2020-03-09 15:12
Oh, I know, but it's the only macro use that causes the warning. Have a stab at it, but since you brought up local time, perhaps after you've rested. Thanks for what you're doing and for the attention you've given so far. <3

**Comment by zer0def** [comment] 2020-03-09 17:06
Alright, Arch's makepkg.conf defaults `CFLAGS` and `CXXFLAGS` to `-O2` and toggling `CFLAGS` to `-O0` causes the build to go through normally. This issue occurs starting from `-O1`, so blame GCC.

**Comment by Veriln** [comment] 2020-04-09 07:19
I've reproduced this on Debian cc 9.3.0. Debug is the only build type to build successfully, which seems to show `-ON` is doing something screwy. I've attached the build opts for curious souls.

Release opts:
```
/usr/bin/cc  -I/home/user/lookingglass/client/include -I/home/user/lookingglass/client/build/include -I/usr/include/x86_64-linux-gnu/SDL2 -I/usr/include/SDL2 -I/home/user/lookingglass/repos/PureSpice/include -I/home/user/lookingglass/repos/PureSpice/src -I/usr/include/spice-1  -O3 -DNDEBUG   -D BUILD_VERSION='"B1-163-g577c54d20d+1"' -D ATOMIC_LOCKING -D GL_GLEXT_PROTOTYPES -D USE_NETTLE -march=native -Wall -Werror -Wfatal-errors -ffast-math -fdata-sections -ffunction-sections -std=gnu11 -o CMakeFiles/purespice.dir/src/spice.c.o   -c /home/user/lookingglass/repos/PureSpice/src/spice.c
```
RelWithDebInfo opts:
```
/usr/bin/cc  -I/home/user/lookingglass/client/include -I/home/user/lookingglass/client/build/include -I/usr/include/x86_64-linux-gnu/SDL2 -I/usr/include/SDL2 -I/home/user/lookingglass/repos/PureSpice/include -I/home/user/lookingglass/repos/PureSpice/src -I/usr/include/spice-1  -O2 -g -DNDEBUG   -D BUILD_VERSION='"B1-163-g577c54d20d+1"' -D ATOMIC_LOCKING -D GL_GLEXT_PROTOTYPES -D USE_NETTLE -march=native -Wall -Werror -Wfatal-errors -ffast-math -fdata-sections -ffunction-sections -std=gnu11 -o CMakeFiles/purespice.dir/src/spice.c.o   -c /home/user/lookingglass/repos/PureSpice/src/spice.c
```
MinSizeRel opts:
```
/usr/bin/cc  -I/home/user/lookingglass/client/include -I/home/user/lookingglass/client/build/include -I/usr/include/x86_64-linux-gnu/SDL2 -I/usr/include/SDL2 -I/home/user/lookingglass/repos/PureSpice/include -I/home/user/lookingglass/repos/PureSpice/src -I/usr/include/spice-1  -Os -DNDEBUG   -D BUILD_VERSION='"B1-163-g577c54d20d+1"' -D ATOMIC_LOCKING -D GL_GLEXT_PROTOTYPES -D USE_NETTLE -march=native -Wall -Werror -Wfatal-errors -ffast-math -fdata-sections -ffunction-sections -std=gnu11 -o CMakeFiles/purespice.dir/src/spice.c.o   -c /home/user/lookingglass/repos/PureSpice/src/spice.c
```

**Comment by DataBeaver** [comment] 2020-04-10 17:32
Well, it doesn't seem to be about the void type at least.  Changing it to any other type still produces the error.  Adding = { 0 } to the declaration of packet does not help either.

While looking at this I found two other things that seem to be screwy with spice_agent_write_msg.

1. You are only calling spice_write_nl to write the actual data on the first iteration of the while loop.  On subsequent iterations SPICE_SEND_PACKET_NL will send the packet header but there's nothing to send the contents.

2. SPICE_PACKET is returning a pointer to an array within the statement expression, which goes out of scope as the expression ends.  The memory will continue to be valid due to the way local variables are allocated, but I'm leery of this being potentially UB (statement expressions are a GCC extension and the docs don't say anything about this particular case).

Maybe that second thing is actually what's causing the warning?  Manually expanding the SPICE_PACKET macro at the problematic location and moving the declaration of packet out of the statement expression fixed it.

**Comment by zer0def** [comment] 2020-04-10 18:44
I guess I should've mentioned back when I originally reported this: when `src/spice.c:1122` (as of `1635f28eab1af01e5948070a4e91dd71675e4008`) line is changed from
`ok = SPICE_SEND_PACKET_NL(&spice.scMain, cont);` to `ok = SPICE_SEND_PACKET(&spice.scMain, cont);` (same macro, just with added locking logic), GCC has no issue merrily chugging along, even though the code itself will deadlock on runtime.

**Comment by DataBeaver** [comment] 2020-04-10 19:23
I retract my statement about the memory contents staying valid.  It turns out that the compiler can optimize away the initializations since it sees the array going out of scope without being used.  This results in completely bogus contents and errors when trying to use the contents.

Here's a patch which moves the array declaration out of the statement expression: http://www.tdb.fi/~tdb/tmp/0001-Fix-packet-declarations.patch

With this I'm able to compile PureSpice and Looking Glass works too.

**Comment by Veriln** [comment] 2020-04-10 21:02
The patch seems to prevent frame updates. Input seems to be working correctly, including mouse tracking, but no changes from the initial frame are passed to the client.

**Comment by DataBeaver** [comment] 2020-04-10 21:04
See the patch I posted in https://github.com/gnif/LookingGlass/issues/248.  Does that resolve the update issue?

**Comment by Veriln** [comment] 2020-04-10 21:17
The combination of the two patches seems to work correctly, including the initial building errors. All build types are successful.

**Comment by gnif** [comment] 2020-04-12 03:41
While this patch clearly works, it seems like we are working around a bug in GCC and as such, I am not inclined to include it. If someone that is good with C can confirm that this is indeed an optimization bug I will raise this with the GCC team.

**Comment by DataBeaver** [comment] 2020-04-12 07:27
I don't believe it's an optimization bug, but rather undefined behaviour in the original code.  A few excerpts from the C standard:

https://en.cppreference.com/w/c/language/storage_duration

> automatic storage duration. The storage is allocated when the block in which the object was declared is entered and deallocated when it is exited by any means (goto, return, reaching the end).

https://en.cppreference.com/w/c/language/lifetime

> For the objects that are declared with automatic, static, and thread storage duration, lifetime equals their storage duration

> Accessing an object outside of its lifetime is undefined behavior.

https://en.cppreference.com/w/c/language/statements#Compound_statements

> A compound statement, or _block_, is a brace-enclosed sequence of statements and declarations.

https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html

> A compound statement enclosed in parentheses may appear as an expression in GNU C.

The SPICE_PACKET macro is declaring an array within a statement expression (which is a block) and then "returning" a pointer to that array out of the block.  However the array's lifetime ends when the block exits, so even though you still have a pointer to the array, accessing it is UB.

If the way I have declared the array outside the block seems too hacky to you I can try to come up with an alternative (global array? alloca?), but based on the standard it seems clear that the code here needs to be fixed.

**Comment by DataBeaver** [comment] 2020-04-12 08:54
I checked the documentation for alloca and several different sources explicitly state that the memory is freed at the end of the function, not at the end of the block where alloca is used.  Statement expressions are not functions, so alloca should be a safe alternative here.  It was originally a BSD extension but is supported by both GNU and Microsoft libc.

Here's a patch with alloca: http://www.tdb.fi/~tdb/tmp/0001-Use-alloca-instead-of-local-array-in-SPICE_PACKET.patch

My VM is currently acting up for unrelated reasons so I have not tested this patch myself yet (other than making sure it compiles).  I will do so later today when I have time to fix the VM.

**Comment by Veriln** [comment] 2020-04-12 19:13
I haven't found any adverse effects to any builds from Beaver's most recent patch.

**Comment by gnif** [comment] 2020-04-13 09:50
@DataBeaver awesome, thanks for the information, this is exactly what I was looking for :). Being self-taught I am by no means complete in my knowledge of the C language or its caveats. I love your solution to use `alloc` and will be switching to it as the intent of this code is to keep it on the stack and avoid `malloc` / `memcpy`.

**Comment by DataBeaver** [comment] 2020-04-13 09:59
I'm glad to hear it was useful.

As a followup to my earlier note about testing, I have now done that and can confirm that the alloca version does work properly with compiler optimizations enabled.

**Closed as completed** 2020-04-13 10:05 UTC
